name: Armadura
version: 0
main: com.github.armadura.Armadura
api-version: 1.21.4
author: magenta555
website: github.com/magenta555/armadura
commands:
  armor:
    description: Opens the armor menu.
    usage: /armor
    permission: armadura.armor
permissions:
  armadura.armor:
    description: Allows players to use the /armor command
    default: true